### ISSUE TITLE
关于图片取模格式

### ISSUE THREAD

**Issue by dfycode** [hello-myj/stm32_oled#2]
作者你好：
### DOC文档没写图片取模格式，我用PCtoLCD2002软件，发现取模格式以下
          

- 点阵格式 阴码
- 取模方式 列行式
- 取模走向 逆向（低位在前）
- 每行显示的数据（16字节）

期待你的文档使用说明

**Comment by hello-myj** [comment]
DOC已经更新好了，取模工具已放入Tool文件夹中。
